import type { Product, Category, Review, BlogPost } from "./types";

export const categories: Category[] = [
  {
    id: "1",
    name: "Traditional Snacks",
    nameTamil: "பாரம்பரிய தின்பண்டங்கள்",
    slug: "traditional-snacks",
    image: "https://images.unsplash.com/photo-1599490659213-e2b9527bd087?w=400&q=80",
    productCount: 24,
    color: "from-maroon-800 to-maroon-600",
  },
  {
    id: "2",
    name: "Pickles",
    nameTamil: "ஊறுகாய்",
    slug: "pickles",
    image: "https://images.unsplash.com/photo-1589927986089-35812388d1f4?w=400&q=80",
    productCount: 18,
    color: "from-gold-600 to-gold-400",
  },
  {
    id: "3",
    name: "Millet Products",
    nameTamil: "சிறுதானிய பொருட்கள்",
    slug: "millet-products",
    image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&q=80",
    productCount: 15,
    color: "from-leaf-700 to-leaf-500",
  },
  {
    id: "4",
    name: "Organic Groceries",
    nameTamil: "இயற்கை மளிகை",
    slug: "organic-groceries",
    image: "https://images.unsplash.com/photo-1542838132-92c53300491e?w=400&q=80",
    productCount: 32,
    color: "from-leaf-600 to-gold-400",
  },
  {
    id: "5",
    name: "Spices & Masalas",
    nameTamil: "மசாலா",
    slug: "spices-masalas",
    image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400&q=80",
    productCount: 28,
    color: "from-orange-700 to-yellow-500",
  },
  {
    id: "6",
    name: "Rice & Grains",
    nameTamil: "அரிசி & தானியங்கள்",
    slug: "rice-grains",
    image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&q=80",
    productCount: 20,
    color: "from-amber-700 to-amber-400",
  },
  {
    id: "7",
    name: "Sweets",
    nameTamil: "இனிப்புகள்",
    slug: "sweets",
    image: "https://images.unsplash.com/photo-1571167093695-07d2ef41d85c?w=400&q=80",
    productCount: 22,
    color: "from-pink-700 to-rose-400",
  },
  {
    id: "8",
    name: "Healthy Mixes",
    nameTamil: "ஆரோக்கிய கலவைகள்",
    slug: "healthy-mixes",
    image: "https://images.unsplash.com/photo-1506976785307-8732e854ad03?w=400&q=80",
    productCount: 16,
    color: "from-teal-700 to-emerald-400",
  },
  {
    id: "9",
    name: "Herbal Products",
    nameTamil: "மூலிகை பொருட்கள்",
    slug: "herbal-products",
    image: "https://images.unsplash.com/photo-1515694346937-94d85e41e6f0?w=400&q=80",
    productCount: 14,
    color: "from-green-800 to-lime-500",
  },
  {
    id: "10",
    name: "Festival Specials",
    nameTamil: "திருவிழா சிறப்புகள்",
    slug: "festival-specials",
    image: "https://images.unsplash.com/photo-1607897883668-44be4c0c8d1f?w=400&q=80",
    productCount: 30,
    color: "from-maroon-800 to-gold-500",
  },
];

export const products: Product[] = [
  {
    id: "1",
    name: "Kambu Health Mix",
    nameTamil: "கம்பு ஆரோக்கிய கலவை",
    slug: "kambu-health-mix",
    category: "Healthy Mixes",
    categorySlug: "healthy-mixes",
    price: 249,
    originalPrice: 349,
    discount: 29,
    rating: 4.8,
    reviewCount: 342,
    image: "https://images.unsplash.com/photo-1506976785307-8732e854ad03?w=500&q=80",
    images: [
      "https://images.unsplash.com/photo-1506976785307-8732e854ad03?w=500&q=80",
      "https://images.unsplash.com/photo-1505253758473-96b7015fcd40?w=500&q=80",
    ],
    description: "Nutritious pearl millet health mix blended with traditional spices and dried fruits. Perfect for a healthy breakfast or evening drink.",
    shortDescription: "Pearl millet health mix with traditional spices",
    ingredients: ["Pearl Millet (Kambu)", "Ragi", "Sesame", "Cardamom", "Dry Ginger", "Palm Sugar"],
    nutritionalInfo: {
      "Calories": "380 kcal/100g",
      "Protein": "12g",
      "Carbohydrates": "68g",
      "Fat": "5g",
      "Fiber": "8g",
    },
    storageInstructions: "Store in a cool, dry place. Use within 6 months of manufacture.",
    weight: "500g",
    isNew: false,
    isBestSeller: true,
    isFeatured: true,
    inStock: true, isVisible: true,
    stockCount: 48,
    tags: ["millet", "health", "breakfast", "organic"],
  },
  {
    id: "2",
    name: "Traditional Murukku",
    nameTamil: "பாரம்பரிய முறுக்கு",
    slug: "traditional-murukku",
    category: "Traditional Snacks",
    categorySlug: "traditional-snacks",
    price: 199,
    originalPrice: 249,
    discount: 20,
    rating: 4.9,
    reviewCount: 589,
    image: "https://images.unsplash.com/photo-1599490659213-e2b9527bd087?w=500&q=80",
    description: "Crispy, crunchy traditional rice flour murukku made with authentic spices. A beloved Tamil Nadu snack passed down through generations.",
    shortDescription: "Crispy traditional rice flour murukku",
    ingredients: ["Rice Flour", "Urad Dal", "Sesame Seeds", "Cumin", "Asafoetida", "Salt", "Coconut Oil"],
    weight: "400g",
    isBestSeller: true,
    isFeatured: true,
    inStock: true, isVisible: true,
    stockCount: 112,
    tags: ["snacks", "traditional", "crispy"],
  },
  {
    id: "3",
    name: "Mango Pickle",
    nameTamil: "மாங்காய் ஊறுகாய்",
    slug: "mango-pickle",
    category: "Pickles",
    categorySlug: "pickles",
    price: 189,
    originalPrice: 229,
    discount: 17,
    rating: 4.7,
    reviewCount: 421,
    image: "https://images.unsplash.com/photo-1589927986089-35812388d1f4?w=500&q=80",
    description: "Tangy, spicy raw mango pickle made with cold-pressed sesame oil and hand-ground spices. A staple condiment in every Tamil kitchen.",
    shortDescription: "Spicy raw mango pickle in sesame oil",
    ingredients: ["Raw Mango", "Sesame Oil", "Red Chilli", "Mustard", "Fenugreek", "Salt"],
    weight: "300g",
    isBestSeller: true,
    isFeatured: true,
    inStock: true, isVisible: true,
    stockCount: 67,
    tags: ["pickle", "spicy", "condiment"],
  },
  {
    id: "4",
    name: "Karupatti Mittai",
    nameTamil: "கருப்பட்டி மிட்டாய்",
    slug: "karupatti-mittai",
    category: "Sweets",
    categorySlug: "sweets",
    price: 159,
    originalPrice: 199,
    discount: 20,
    rating: 4.6,
    reviewCount: 287,
    image: "https://images.unsplash.com/photo-1571167093695-07d2ef41d85c?w=500&q=80",
    description: "Traditional palm sugar candy with rich, complex flavor. Made with unprocessed palm jaggery — naturally sweet and packed with minerals.",
    shortDescription: "Traditional palm sugar candy",
    weight: "250g",
    isFeatured: true,
    isNew: true,
    inStock: true, isVisible: true,
    stockCount: 34,
    tags: ["sweets", "traditional", "palm sugar"],
  },
  {
    id: "5",
    name: "Millet Cookies",
    nameTamil: "சிறுதானிய குக்கீஸ்",
    slug: "millet-cookies",
    category: "Millet Products",
    categorySlug: "millet-products",
    price: 179,
    originalPrice: 229,
    discount: 22,
    rating: 4.5,
    reviewCount: 198,
    image: "https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=500&q=80",
    description: "Wholesome, guilt-free cookies made from a blend of foxtail millet, finger millet, and natural sweeteners. Perfect healthy snack for all ages.",
    shortDescription: "Healthy millet-based cookies",
    weight: "300g",
    isFeatured: true,
    isNew: true,
    inStock: true, isVisible: true,
    stockCount: 55,
    tags: ["millet", "cookies", "healthy", "snacks"],
  },
  {
    id: "6",
    name: "Organic Turmeric Powder",
    nameTamil: "இயற்கை மஞ்சள் தூள்",
    slug: "organic-turmeric-powder",
    category: "Spices & Masalas",
    categorySlug: "spices-masalas",
    price: 129,
    originalPrice: 169,
    discount: 24,
    rating: 4.9,
    reviewCount: 672,
    image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=500&q=80",
    description: "Pure, stone-ground turmeric powder from native Erode turmeric farms. High curcumin content, naturally processed without chemicals.",
    shortDescription: "Pure Erode turmeric, high curcumin",
    weight: "200g",
    isBestSeller: true,
    isFeatured: true,
    inStock: true, isVisible: true,
    stockCount: 89,
    tags: ["spices", "organic", "turmeric"],
  },
  {
    id: "7",
    name: "Homemade Idli Podi",
    nameTamil: "இட்லி பொடி",
    slug: "homemade-idli-podi",
    category: "Spices & Masalas",
    categorySlug: "spices-masalas",
    price: 149,
    originalPrice: 189,
    discount: 21,
    rating: 4.8,
    reviewCount: 534,
    image: "https://images.unsplash.com/photo-1574484284002-952d92456975?w=500&q=80",
    description: "Authentic homestyle gun powder (idli podi) with sesame seeds and roasted lentils. The perfect companion for idli, dosa, and more.",
    shortDescription: "Authentic gun powder spice blend",
    weight: "200g",
    isBestSeller: true,
    isFeatured: true,
    inStock: true, isVisible: true,
    stockCount: 73,
    tags: ["spices", "traditional", "condiment"],
  },
  {
    id: "8",
    name: "Herbal Tea Mix",
    nameTamil: "மூலிகை தேநீர் கலவை",
    slug: "herbal-tea-mix",
    category: "Herbal Products",
    categorySlug: "herbal-products",
    price: 219,
    originalPrice: 279,
    discount: 21,
    rating: 4.7,
    reviewCount: 312,
    image: "https://images.unsplash.com/photo-1515694346937-94d85e41e6f0?w=500&q=80",
    description: "Soothing herbal tea blend with tulsi, pepper, ginger, cardamom, and more. Traditional immunity-boosting recipe from Tamil Nadu households.",
    shortDescription: "Traditional immunity-boosting herbal tea",
    weight: "100g",
    isFeatured: true,
    isNew: true,
    inStock: true, isVisible: true,
    stockCount: 41,
    tags: ["herbal", "tea", "immunity", "health"],
  },
  {
    id: "9",
    name: "Thinai (Foxtail Millet) Rice",
    nameTamil: "தினை அரிசி",
    slug: "thinai-foxtail-millet-rice",
    category: "Millet Products",
    categorySlug: "millet-products",
    price: 169,
    originalPrice: 199,
    discount: 15,
    rating: 4.6,
    reviewCount: 156,
    image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=500&q=80",
    description: "Ancient foxtail millet grain, high in fiber and protein. Cook just like regular rice for a nutritious, diabetic-friendly meal.",
    shortDescription: "Ancient foxtail millet grain",
    weight: "1kg",
    inStock: true, isVisible: true,
    isNew: true,
    stockCount: 28,
    tags: ["millet", "rice", "organic", "diabetic-friendly"],
  },
  {
    id: "10",
    name: "Avakkai Pickle",
    nameTamil: "அவக்காய் ஊறுகாய்",
    slug: "avakkai-pickle",
    category: "Pickles",
    categorySlug: "pickles",
    price: 199,
    originalPrice: 249,
    discount: 20,
    rating: 4.8,
    reviewCount: 389,
    image: "https://images.unsplash.com/photo-1589927986089-35812388d1f4?w=500&q=80",
    description: "Bold, fiery Andhra-style raw mango avakkai pickle. Made with mustard seeds, fenugreek, and red chili for an intense, authentic taste.",
    shortDescription: "Fiery Andhra-style mango pickle",
    weight: "300g",
    isBestSeller: true,
    inStock: true, isVisible: true,
    stockCount: 0,
    tags: ["pickle", "spicy", "mango"],
  },
  {
    id: "11",
    name: "Organic Groundnut Oil",
    nameTamil: "இயற்கை நிலக்கடலை எண்ணெய்",
    slug: "organic-groundnut-oil",
    category: "Organic Groceries",
    categorySlug: "organic-groceries",
    price: 389,
    originalPrice: 449,
    discount: 13,
    rating: 4.9,
    reviewCount: 478,
    image: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=500&q=80",
    description: "Cold-pressed, unrefined groundnut oil extracted using traditional wooden churner (marachekku). Rich in flavor and natural nutrients.",
    shortDescription: "Cold-pressed traditional groundnut oil",
    weight: "1L",
    isBestSeller: true,
    inStock: true, isVisible: true,
    stockCount: 19,
    tags: ["oil", "organic", "cold-pressed"],
  },
  {
    id: "12",
    name: "Pottukadalai Laddu",
    nameTamil: "பொட்டுக்கடலை லட்டு",
    slug: "pottukadalai-laddu",
    category: "Sweets",
    categorySlug: "sweets",
    price: 229,
    originalPrice: 279,
    discount: 18,
    rating: 4.7,
    reviewCount: 243,
    image: "https://images.unsplash.com/photo-1571167093695-07d2ef41d85c?w=500&q=80",
    description: "Delicious roasted chickpea laddus sweetened with jaggery and flavored with cardamom. A traditional Tamil Nadu sweet for all occasions.",
    shortDescription: "Jaggery-sweetened roasted chickpea laddu",
    weight: "400g",
    inStock: true, isVisible: true,
    stockCount: 62,
    tags: ["sweets", "laddu", "traditional"],
  },
];

export const reviews: Review[] = [
  {
    id: "1",
    name: "Priya Sundarajan",
    location: "Chennai, Tamil Nadu",
    rating: 5,
    review: "Amma's Akshayam murukku tastes exactly like my grandmother's homemade one! The packaging is perfect and delivery was super fast. Will definitely order again.",
    date: "2026-05-15",
    avatar: "https://images.unsplash.com/photo-1494790108755-2616b612b47c?w=100&q=80",
    verified: true,
  },
  {
    id: "2",
    name: "Karthikeyan Murugan",
    location: "Coimbatore, Tamil Nadu",
    rating: 5,
    review: "The organic turmeric powder is amazing. You can tell the difference from store-bought immediately — much more aromatic and flavorful. Highly recommend!",
    date: "2026-05-10",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&q=80",
    verified: true,
  },
  {
    id: "3",
    name: "Meenakshi Devi",
    location: "Madurai, Tamil Nadu",
    rating: 5,
    review: "The idli podi is outstanding! My kids who normally don't eat idli now ask for it every morning. The quality is truly homemade standard.",
    date: "2026-05-08",
    avatar: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=100&q=80",
    verified: true,
  },
  {
    id: "4",
    name: "Rajan Pillay",
    location: "Tirunelveli, Tamil Nadu",
    rating: 4,
    review: "Excellent kambu health mix. I've been using it for 3 months now for my morning drink. Noticed improvement in energy levels. Packaging could be slightly better.",
    date: "2026-05-01",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&q=80",
    verified: true,
  },
  {
    id: "5",
    name: "Lakshmi Nair",
    location: "Salem, Tamil Nadu",
    rating: 5,
    review: "Ordered mango pickle and avakkai together. Both are perfectly balanced in spice and sourness. Reminds me of home-cooked tradition. Absolutely love this brand!",
    date: "2026-04-28",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&q=80",
    verified: true,
  },
  {
    id: "6",
    name: "Selvam Annamalai",
    location: "Thanjavur, Tamil Nadu",
    rating: 5,
    review: "The millet cookies are a game changer for healthy snacking. My diabetic father loves them. Natural sweetness and crunchy texture is perfect!",
    date: "2026-04-20",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&q=80",
    verified: true,
  },
];

export const blogPosts: BlogPost[] = [
  {
    id: "1",
    title: "The Health Benefits of Millet: Why Our Ancestors Were Right",
    slug: "health-benefits-of-millet",
    excerpt: "Discover why millets like kambu, ragi, and thinai are being called superfoods and how incorporating them into your diet can transform your health.",
    content: "",
    image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=800&q=80",
    author: "Amma's Akshayam Team",
    date: "2026-05-20",
    category: "Health Benefits",
    readTime: 6,
    tags: ["millet", "health", "nutrition"],
  },
  {
    id: "2",
    title: "Pongal Recipes: Celebrating Tamil Harvest Traditions",
    slug: "pongal-recipes-tamil-harvest-traditions",
    excerpt: "Explore authentic Pongal recipes and the cultural significance of this beloved harvest festival. From sweet pongal to ven pongal — your complete guide.",
    content: "",
    image: "https://images.unsplash.com/photo-1607897883668-44be4c0c8d1f?w=800&q=80",
    author: "Kamala Sundaram",
    date: "2026-05-15",
    category: "Festival Foods",
    readTime: 8,
    tags: ["pongal", "festival", "recipe"],
  },
  {
    id: "3",
    title: "Why Choose Cold-Pressed Oils Over Refined Oils",
    slug: "cold-pressed-vs-refined-oils",
    excerpt: "Understand the key differences between cold-pressed and refined cooking oils, and why switching to traditional marachekku oils benefits your family's health.",
    content: "",
    image: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=800&q=80",
    author: "Dr. Priya Natarajan",
    date: "2026-05-10",
    category: "Organic Living",
    readTime: 5,
    tags: ["oil", "organic", "cooking"],
  },
  {
    id: "4",
    title: "Homemade Murukku: The Art of the Perfect Crunch",
    slug: "homemade-murukku-recipe",
    excerpt: "Step-by-step guide to making crispy, golden murukku at home using traditional methods. Includes tips from our master chefs in Tamil Nadu.",
    content: "",
    image: "https://images.unsplash.com/photo-1599490659213-e2b9527bd087?w=800&q=80",
    author: "Amma's Akshayam Team",
    date: "2026-05-05",
    category: "Homemade Recipes",
    readTime: 10,
    tags: ["murukku", "recipe", "snacks"],
  },
];

export const tamilNaduRegions = [
  { name: "Chennai", x: 78, y: 35, orders: 2847 },
  { name: "Coimbatore", x: 38, y: 58, orders: 1923 },
  { name: "Madurai", x: 55, y: 72, orders: 1567 },
  { name: "Trichy", x: 60, y: 60, orders: 1234 },
  { name: "Salem", x: 48, y: 48, orders: 987 },
  { name: "Tirunelveli", x: 50, y: 88, orders: 876 },
  { name: "Thanjavur", x: 68, y: 65, orders: 765 },
  { name: "Vellore", x: 62, y: 32, orders: 654 },
];
